### ISSUE TITLE
Aggregate filter not run at all

### ISSUE THREAD

**Issue by CamJN** [logstash-plugins/logstash-filter-aggregate#21] opened 2016-01-19 22:24 UTC
I'm trying to carry forward a year that is specified infrequently in my logs, and it seemed like the aggregate filter would work beautifully for this, however the filter doesn't seem to actually do anything (I've added the add_tag setting to see if the code was the only problem and the tag wasn't added either) other blocks in the same part of the conditional run fine (I get the one and two lines printed to stdout given the correct input).

```
if ([timestamp] !~ /.+/) {
   drop {}
} else if ([message] =~ /^started/) {
   ruby {code=>"puts 'one'"}
   aggregate {
      task_id => "%{path}"
      code => "map['year'] = Time.at(event['timestamp'].to_f).year"
      add_tag => ['hi']
   }
} else {
   ruby {code=>"puts 'two'"}
   aggregate {
      task_id => "%{path}"
       code => "event['timestamp'].gsub!(/(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)/,map['year'].to_s+' \1')"
       map_action => "update"
       add_tag => ['there']
   }
}
```

**Comment by alkuzad** [comment] 2016-01-20 10:11
do you have any aggregate filter with `end_of_task => true` ?

**Comment by fbaligand** [comment] 2016-01-20 10:43
Questions :
- Are you sure `path` field has a value and is not empty ?
- Have you watched logstash logs to check that no error is logged by aggregate filter (when it executes `code` section) ?
- In the `else` block, are you sure that map has always been created before ? I mean `map_action=>"update"` implies that code will be executed and tag will be added only if map already exist for this task_id.
- can you give some input log example ?

**Comment by CamJN** [comment] 2016-01-20 15:22
I don't have any aggregate filter with `end_of_task => true`, as I don't want to delete the map. the path field definately has a value, I hard-coded it for testing. The logstash logs at `/var/log/logstash/*` are empty, are there any others? the line that `create_or_update`s the map is always first in my logs.


My simple example I was testing against was:
```
Resetting the coordinator, waiting 30 seconds...
-nwkwait 480
-intr 4
-stayAwake 0
-port ttyO1
-platform BBB
-attempts 6


started at 1412205541.26, local 2014-10-01 23:19:01
[Oct 01, 23:19:01: network] request status for 0
```

The first 9 lines get dropped for having no timestamp, then the 10th line should set the year in the map, and the 11th line should use the map to update the timestamp field.

**Comment by fbaligand** [comment] 2016-01-21 22:58
I just tested exactly your code, with your sample data, and it worked fine.

At the end, I got : 
```
{
     "timestamp" => "2014 Oct 01, 23:19:01",
          "tags" => ["there"],
          "year" => 2014
}
```

So I'm very surprised it doesn't work for you.

Maybe one thing : 
To be sure that events are processed in the right order by aggregate filter, you have to add `-w 1` command line flag in your logstash startup

**Comment by CamJN** [comment] 2016-01-21 23:00
My config already enforces a single worker because it uses the multiline filter. I'm baffled as to why this doesn't work. But as a workaround I've basically recreated the same using `ruby{}` blocks.

**Comment by fbaligand** [comment] 2016-01-21 23:14
OK. 
So now you say me you use multiline filter, I think the problem is tied to that.
This filter is particular and I would not be surprised it doesn't work well with aggregate plugin.

Anyway, up to me, it's surprising to see you use these 2 plugins together. 
If I understand well your need, you want to concat year and time in a same "timestamp" field. Right ?
If you use multiline filter, year and time are in the same message. 
So you don't need aggregate filter, which is usefull to aggregate informations present in different messages.

**Comment by CamJN** [comment] 2016-01-21 23:27
Sorry, I didn't realize that my setup was that unusual, and I didn't mention everything because it's rather large. I'll try and explain better. I use the multiline filter to combine certain lines, because a few kinds of log lines use multiple lines. But this isn't meant to be related to the year thing, just making each event be consolidated to one line.

I then run grok to parse and tokenize my logs; at which point about 1% of lines have a timestamp that specifies the year. The rest only have the month, day, and time. What I want to do, is to carry forward the year from the lines that have a year to all subsequent lines and update the year every time I come across one. And have all that be per file-path so as not to mix up my data. And then the date is parsed.

There are a bunch of additional steps that I could describe too but which don't involve the timestamp at all, like adding and removing fields, splitting fields into arrays, text manipulations, translations, and type conversions.

**Comment by fbaligand** [comment] 2016-01-22 08:53
Okay. 
So :
- the first thing is that your aggregate filter configuration is correct. I tested it yesterday, it works. I will send you tonight my full logstash configuration test. 
- this means also there is no bug in aggregate filter. 
- so the problem is tied to your previous filters before aggregate. And I really think this is because of multiline filter. 
- so could you test to move multiline filter configuration after aggregate configuration ?

Fabien

**Comment by fbaligand** [comment] 2016-01-23 16:49
As promised, the full logstash configuration I used to test your use case :

```
input {
	stdin {
		type => "stdin"
	}
}

filter {

	mutate {
		add_field => {
			"path" => "/path"
		}
	}

	#if ([timestamp] !~ /.+/) {
	#   drop {}
	#} else 
	if ([message] =~ /^started/) {

	   ruby {code=>"puts 'one'"}
	
		mutate {
			add_field => {
				"timestamp" => "1412205541.26" 
			}
		}
	
	   aggregate {
		  task_id => "%{path}"
		  code => "map['year'] = Time.at(event['timestamp'].to_f).year"
		  add_tag => ['hi']
	   }
	}
	else {
	   ruby {code=>"puts 'two'"}

		mutate {
			add_field => {
				"timestamp" => "Oct 01, 23:19:01" 
			}
		}
	
	   aggregate {
		  task_id => "%{path}"
		   code => "event['timestamp'].gsub!(/(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)/,map['year'].to_s+' \1')"
		   map_action => "update"
		   add_tag => ['there']
	   }

		aggregate {
			task_id => "%{path}"
			code => "event['year'] = map['year']"
			map_action => "update"
			end_of_task => true
		}

   }

}

output {
	stdout {
		codec => rubydebug
	}
}
```

Some precisions :
- I commented your first "if", because I force timestamp field later in configuration
- I copy at the end, "year" field from map to event, so that I can display it in output console
- when launching the test, I write 2 lines in "stdin" : "started" and "secondLine", so that I generate 2 messages that match the 2 interesting "if" conditions.
- And at the end, I get a timestamp field with year and time. And I get also the expected tags in document.

**Comment by fbaligand** [comment] 2016-04-26 20:31
The question is answered.
So I close the issue.

**Closed by fbaligand** 2016-04-26 20:31 UTC
Labels: question
