### ISSUE TITLE
Logstash Filter Aggregate (2.6.3) - timeout push does't work

### ISSUE THREAD

**Issue by joelftds** [logstash-plugins/logstash-filter-aggregate#78] opened 2017-12-14 13:37 UTC
I'm running Logstash version 5.6.3-1 with the aggregate plugin version 2.6.3 .
This is a snip from the relevant part from my Logstash config:

```
if [program] == "sophos-message" {
    aggregate {
      task_id => "%{logsource}%{sophos-message_queueid}"
      code => "
      map ||= {}
      event.to_hash.each { |k,v|
        if k.to_s !~ /\@.+/
          map[k] ||= []
          if !map[k].is_a?(Array) then map[k] = [map[k]] end
          if v.is_a?(Array) then map[k] |= v else map[k] |= [v] end
          if map[k].count == 1 then map[k] = map[k].first end
        end
      }
      map.each { |k,v|
        event.set(k, v)
      }
      "
      map_action => "create_or_update"
      inactivity_timeout => 10
      timeout => 1800
      push_map_as_event_on_timeout => true
      end_of_task => true
      timeout_task_id_field => 'aggr_taskid'
      timeout_tags => ['_aggr_sophos_timeout']
      add_tag => ['_aggr_sophos_end', '_aggr_sophos_end_1' ]
    }
    if "_aggr_sophos_end_2" not in [tags] {
      aggregate {
        task_id => "%{logsource}%{sophos-message_queueid}"
        code => "
        map ||= {}
        event.to_hash.each { |k,v|
          if k.to_s !~ /\@.+/
            map[k] ||= []
            if !map[k].is_a?(Array) then map[k] = [map[k]] end
            if v.is_a?(Array) then map[k] |= v else map[k] |= [v] end
            if map[k].count == 1 then map[k] = map[k].first end
          end
        }
        event.cancel()
        "
        map_action => "create"
      }
    }
  }
```

With the first aggregation, I want to end the aggregation with "end_of_task". After that I can check if a tag is present in my event.
If the tag is not present,  the event should be aggregate again with the same task id.
Now my problem. If there comes after the second aggregation no "end_of_task" part, I want that the "inactivity_timeout" push this event after 10 seconds as a new event (push_map_as_event_on_timeout). But this doesn't happens. The event is never send to elasticsearch. I can't declare the timeout options at the second aggregation again, because it has the same task id as the first. Is this a bug? Where is the problem?

**Comment by fbaligand** [comment] 2017-12-16 09:25
First, a little remark : `map ||= {}` is useless, because aggregate plugin still initiates it before calling aggregate `code`.

Then, indeed, all timeout options have to be defined in only one aggregate filter per task_id pattern (it is indicated in documentation).
And it's not a bug, but a feature :)
Explanation : all task maps are shared between all aggregate filters. 
Then, timeout management is processed per task_id pattern. So when timeout management is launched, if several aggregate filters define timeout options, it couldn't know which options it should apply. That's the problem, and that's why you can't define timeout options on several aggregate filters.

That said, if you want to have a second independent aggregate process (with a different map per task), you can define a different task id pattern, using a static prefix. For example : 
`task_id => "_aggr_sophos_end_2_%{logsource}%{sophos-message_queueid}"`

**Comment by fbaligand** [comment] 2018-01-15 10:47
No answer for one month, so I close the issue.

**Closed by fbaligand** 2018-01-15 10:47 UTC
Labels: question
