### ISSUE TITLE
Catch and log exceptions during code call execution

### ISSUE THREAD

**Issue by alkuzad** [logstash-plugins/logstash-filter-aggregate#5] opened 2015-09-22 12:49 UTC
I have rather complex aggregate setup. Sometimes there is an exceptions in one of the codes and it's really hard to get the view of the error.

Do you think it's good idea to re-raise exception with proper `@codeblock` data ? The simplest way should be simple include `@code` into exception so it's a lot easier to find out where the invalid code is.

I've monkey patched `@codeblock.call` to something like this

```ruby
begin
   @codeblock.call(event, map)
rescue => exception
   raise RuntimeError.new("There is an error with \n#{@code}\n, Error:\n#{exception}")
end
```
It's not best idea but at least I have the `@code` which is likely to be unique in my setup.

**Comment by fbaligand** [comment] 2015-09-22 21:05
Hi @alkuzad,

It's odd to see that I had exactly the same problem (and idea) than you, nearly in the same time :)

To fix the problem, I suggest to do exactly the same thing that this code :
https://github.com/logstash-plugins/logstash-filter-ruby/blob/master/lib/logstash/filters/ruby.rb#L40

It allows to keep logstash up (and not crash logstash), log error when it occurs with @code section, and tag the event that caused the problem.

Makes sense to you  ?

I consider to code it and make the pull request for it this thurday, in the evening.

**Comment by alkuzad** [comment] 2015-09-23 16:37
Hi @fbaligand 

Yes this is even better :) I personally extended the printout to include current `map` and event `@data` to find out errors quickly but I do not know if the @logger.error should add event automatically.

**Comment by fbaligand** [comment] 2015-09-23 16:58
@alkuzad Can you put your code here ?

**Comment by alkuzad** [comment] 2015-09-25 09:16
Hi @fbaligand 

It's something like this:

```ruby
begin
  @codeblock.call(event, map)
rescue => exception
  raise RuntimeError.new("There is an error with \n#{@code}\n, Error:\n#{exception}, Map: #{map}, EventData: #{event.instance_variable_get('@data')}")
end
```

```
input{
  stdin {}
}

filter{
  grok{
    match => { "[message]" => "%{NUMBER:id};(?<foo>.*)" }
  }

  if [id] {
    aggregate {
        task_id => "test_%{id}"
        code => "fail 'Asd';"
        map_action => "create"
        end_of_task => true
      }
  }
}

output {
  stdout { codec => rubydebug }
}
```

**Comment by fbaligand** [comment] 2015-09-25 09:35
Thank you @alkuzad. 

I will draw inspiration from your code to log error.

**Comment by fbaligand** [comment] 2015-10-16 09:55
@alkuzad
The issue is now fixed.

To get it using logstash 1.5, use aggregate plugin version 0.1.4.
To get it using logstash 2.0, use aggregate plugin version 2.0.2.

**Comment by alkuzad** [comment] 2015-10-16 15:01
@fbaligand thanks for fixing that :) I will check that when I'm done with fixing my ELK ansible setup :)

**Comment by fbaligand** [comment] 2015-10-16 15:59
@alkuzad 
OK. Let me know when you will check :)

**Closed** 2015-11-14 14:26 UTC
Labels: bug, v0.1.4, v2.0.2

**Comment by alkuzad** [comment] 2015-12-01 15:52
Just playing with ELK again, works like a charm :)

**Comment by fbaligand** [comment] 2015-12-01 17:24
Nice to hear that !
